name: Artifact Workflow

on:
  push:
    branches:
      - main  # Use your branch name if it's not main

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create sample.txt
        run: echo "Sample artifact content" > sample.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-text
          path: sample.txt

  use_artifact:
    runs-on: ubuntu-latest
    needs: create_artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sample-text

      - name: Display file content
        run: cat sample.txt

